---
apiVersion: v1
kind: Service
metadata:
  name: hello-server-external
spec:
  type: NodePort
  selector:
    app: hello-serve
  ports:
    - protocol: TCP
      port: 8081 # serviceが受け付けるPort
      targetPort: 8080 # 利用するコンテナが開放しているPort
      nodePort: 30599
