apiVersion: v1
kind: Service
metadata:
  name: hello-server-external
spec:
  type: NodePort
  selector:
    app: hello-server # サービスを利用したいPodのラベルと一致させる
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081 # 利用するコンテナが開放しているPortを指定する
      nodePort: 30599
